// This file is autogenerated, do not modify it.

export interface Position {
  line: number;
  column: number;
}

interface SourceLocation {
  source?: string | null;
  start: Position;
  end: Position;
}

export interface BaseNode {
  type: string;
  loc?: SourceLocation | null;
  range?: [number, number];
}

export interface Comment extends BaseNode {
  type: 'Line' | 'Block';
  value: string;
}

export interface ArrayExpression extends BaseNode {
  type: 'ArrayExpression';
  elements: Array<
    | ArrayExpression
    | ArrowFunctionExpression
    | AssignmentExpression
    | AwaitExpression
    | BigIntLiteral
    | BinaryExpression
    | CallExpression
    | ConditionalExpression
    | FunctionExpression
    | Identifier
    | JSXElement
    | Literal
    | LogicalExpression
    | MemberExpression
    | NewExpression
    | ObjectExpression
    | SequenceExpression
    | SpreadElement
    | TemplateLiteral
    | ThisExpression
    | UnaryExpression
    | YieldExpression
    | TSAsExpression
    | TSNonNullExpression
    | TSTypeAssertion
    | null
  >;
}

export interface ArrayPattern extends BaseNode {
  type: 'ArrayPattern';
  optional?: boolean;
  typeAnnotation?: TSTypeAnnotation;
  elements: Array<
    | ArrayPattern
    | AssignmentPattern
    | Identifier
    | Literal
    | MemberExpression
    | ObjectPattern
    | RestElement
    | null
  >;
}

export interface ArrowFunctionExpression extends BaseNode {
  type: 'ArrowFunctionExpression';
  generator: boolean;
  expression: boolean;
  async: boolean;
  typeParameters?: TSTypeParameterDeclaration;
  returnType?: TSTypeAnnotation;
  params: Array<
    | ArrayPattern
    | AssignmentPattern
    | Identifier
    | ObjectPattern
    | RestElement
    | TSParameterProperty
  >;
  id: null;
  body:
    | ArrayExpression
    | ArrowFunctionExpression
    | AssignmentExpression
    | AwaitExpression
    | BinaryExpression
    | BlockStatement
    | CallExpression
    | ClassExpression
    | ConditionalExpression
    | FunctionExpression
    | Identifier
    | JSXElement
    | Literal
    | LogicalExpression
    | MemberExpression
    | MetaProperty
    | NewExpression
    | ObjectExpression
    | SequenceExpression
    | TemplateLiteral
    | ThisExpression
    | UnaryExpression
    | YieldExpression
    | TSAsExpression
    | TSNonNullExpression
    | TSTypeAssertion;
}

export interface AssignmentExpression extends BaseNode {
  type: 'AssignmentExpression';
  operator:
    | '%='
    | '&='
    | '**='
    | '*='
    | '+='
    | '-='
    | '/='
    | '<<='
    | '='
    | '>>='
    | '>>>='
    | '^='
    | '|=';
  right:
    | ArrayExpression
    | ArrowFunctionExpression
    | AssignmentExpression
    | AwaitExpression
    | BigIntLiteral
    | BinaryExpression
    | CallExpression
    | ClassExpression
    | ConditionalExpression
    | FunctionExpression
    | Identifier
    | JSXElement
    | Literal
    | LogicalExpression
    | MemberExpression
    | MetaProperty
    | NewExpression
    | ObjectExpression
    | SequenceExpression
    | TemplateLiteral
    | ThisExpression
    | UnaryExpression
    | UpdateExpression
    | YieldExpression
    | TSAsExpression
    | TSNonNullExpression
    | TSTypeAssertion;
  left:
    | ArrayPattern
    | CallExpression
    | Identifier
    | Literal
    | MemberExpression
    | MetaProperty
    | NewExpression
    | ObjectPattern
    | OptionalMemberExpression
    | SequenceExpression
    | TSNonNullExpression;
}

export interface AssignmentPattern extends BaseNode {
  type: 'AssignmentPattern';
  right:
    | ArrayExpression
    | ArrowFunctionExpression
    | AwaitExpression
    | BinaryExpression
    | CallExpression
    | ClassExpression
    | ConditionalExpression
    | FunctionExpression
    | Identifier
    | Literal
    | LogicalExpression
    | MemberExpression
    | NewExpression
    | ObjectExpression
    | TemplateLiteral
    | ThisExpression
    | UnaryExpression
    | YieldExpression
    | TSNonNullExpression;
  left: ArrayPattern | Identifier | ObjectPattern;
}

export interface AwaitExpression extends BaseNode {
  type: 'AwaitExpression';
  argument:
    | CallExpression
    | ConditionalExpression
    | Identifier
    | Literal
    | MemberExpression
    | NewExpression
    | ObjectExpression
    | ThisExpression;
}

export interface BigIntLiteral extends BaseNode {
  type: 'BigIntLiteral';
  value: string;
  raw: string;
}

export interface BinaryExpression extends BaseNode {
  type: 'BinaryExpression';
  operator:
    | '!='
    | '!=='
    | '%'
    | '&'
    | '*'
    | '**'
    | '+'
    | '-'
    | '/'
    | '<'
    | '<<'
    | '<='
    | '=='
    | '==='
    | '>'
    | '>='
    | '>>'
    | '>>>'
    | '^'
    | 'in'
    | 'instanceof'
    | '|';
  right:
    | ArrayExpression
    | ArrowFunctionExpression
    | AwaitExpression
    | BigIntLiteral
    | BinaryExpression
    | CallExpression
    | ConditionalExpression
    | FunctionExpression
    | Identifier
    | Literal
    | LogicalExpression
    | MemberExpression
    | NewExpression
    | ObjectExpression
    | TemplateLiteral
    | ThisExpression
    | UnaryExpression
    | UpdateExpression
    | TSAsExpression
    | TSNonNullExpression
    | TSTypeAssertion;
  left:
    | ArrowFunctionExpression
    | AssignmentExpression
    | AwaitExpression
    | BigIntLiteral
    | BinaryExpression
    | CallExpression
    | ConditionalExpression
    | FunctionExpression
    | Identifier
    | Literal
    | LogicalExpression
    | MemberExpression
    | NewExpression
    | ObjectExpression
    | OptionalCallExpression
    | OptionalMemberExpression
    | SequenceExpression
    | TemplateLiteral
    | ThisExpression
    | UnaryExpression
    | UpdateExpression
    | YieldExpression
    | TSAsExpression
    | TSNonNullExpression;
}

export interface BlockStatement extends BaseNode {
  type: 'BlockStatement';
  body: Array<
    | BlockStatement
    | BreakStatement
    | ClassDeclaration
    | ContinueStatement
    | DebuggerStatement
    | DoWhileStatement
    | EmptyStatement
    | ExportAllDeclaration
    | ExportDefaultDeclaration
    | ExportNamedDeclaration
    | ExpressionStatement
    | ForInStatement
    | ForOfStatement
    | ForStatement
    | FunctionDeclaration
    | IfStatement
    | ImportDeclaration
    | LabeledStatement
    | ReturnStatement
    | SwitchStatement
    | ThrowStatement
    | TryStatement
    | VariableDeclaration
    | WhileStatement
    | WithStatement
    | TSDeclareFunction
    | TSEnumDeclaration
    | TSExportAssignment
    | TSImportEqualsDeclaration
    | TSInterfaceDeclaration
    | TSModuleDeclaration
    | TSTypeAliasDeclaration
  >;
}

export interface BreakStatement extends BaseNode {
  type: 'BreakStatement';
  label: null | Identifier;
}

export interface CallExpression extends BaseNode {
  type: 'CallExpression';
  optional: boolean;
  typeParameters?: TSTypeParameterInstantiation;
  callee:
    | ArrowFunctionExpression
    | AwaitExpression
    | CallExpression
    | ConditionalExpression
    | FunctionExpression
    | Identifier
    | Import
    | Literal
    | LogicalExpression
    | MemberExpression
    | NewExpression
    | SequenceExpression
    | Super
    | YieldExpression
    | TSAsExpression
    | TSNonNullExpression;
  arguments: Array<
    | ArrayExpression
    | ArrowFunctionExpression
    | AssignmentExpression
    | AwaitExpression
    | BigIntLiteral
    | BinaryExpression
    | CallExpression
    | ClassExpression
    | ConditionalExpression
    | FunctionExpression
    | Identifier
    | Literal
    | LogicalExpression
    | MemberExpression
    | NewExpression
    | ObjectExpression
    | OptionalMemberExpression
    | SequenceExpression
    | SpreadElement
    | TaggedTemplateExpression
    | TemplateLiteral
    | ThisExpression
    | UnaryExpression
    | UpdateExpression
    | YieldExpression
    | TSAsExpression
    | TSNonNullExpression
    | TSTypeAssertion
  >;
}

export interface CatchClause extends BaseNode {
  type: 'CatchClause';
  param: null | ArrayPattern | Identifier | ObjectPattern;
  body: BlockStatement;
}

export interface ClassBody extends BaseNode {
  type: 'ClassBody';
  body: Array<
    | ClassProperty
    | MethodDefinition
    | TSAbstractClassProperty
    | TSAbstractMethodDefinition
    | TSIndexSignature
  >;
}

export interface ClassDeclaration extends BaseNode {
  type: 'ClassDeclaration';
  declare?: boolean;
  abstract?: boolean;
  typeParameters?: TSTypeParameterDeclaration;
  superTypeParameters?: TSTypeParameterInstantiation;
  superClass:
    | null
    | AwaitExpression
    | CallExpression
    | ClassExpression
    | Identifier
    | Literal
    | MemberExpression
    | YieldExpression;
  implements?: Array<TSClassImplements>;
  id: null | Identifier;
  decorators?: Array<Decorator>;
  body: ClassBody;
}

export interface ClassExpression extends BaseNode {
  type: 'ClassExpression';
  typeParameters?: TSTypeParameterDeclaration;
  superTypeParameters?: TSTypeParameterInstantiation;
  superClass:
    | null
    | CallExpression
    | ClassExpression
    | Identifier
    | MemberExpression
    | YieldExpression
    | TSAsExpression;
  implements?: Array<TSClassImplements>;
  id: null | Identifier;
  body: ClassBody;
}

export interface ClassProperty extends BaseNode {
  type: 'ClassProperty';
  static: boolean;
  readonly?: boolean;
  optional?: boolean;
  definite?: boolean;
  declare: boolean;
  computed: boolean;
  accessibility?: 'private' | 'protected' | 'public';
  value:
    | null
    | ArrayExpression
    | ArrowFunctionExpression
    | AssignmentExpression
    | AwaitExpression
    | BinaryExpression
    | CallExpression
    | ClassExpression
    | FunctionExpression
    | Identifier
    | Literal
    | LogicalExpression
    | MemberExpression
    | NewExpression
    | ObjectExpression
    | UnaryExpression
    | UpdateExpression
    | YieldExpression;
  typeAnnotation?: TSTypeAnnotation;
  key:
    | AssignmentExpression
    | AwaitExpression
    | CallExpression
    | Identifier
    | Literal
    | MemberExpression
    | YieldExpression;
  decorators?: Array<Decorator>;
}

export interface ConditionalExpression extends BaseNode {
  type: 'ConditionalExpression';
  test:
    | ArrayExpression
    | ArrowFunctionExpression
    | AssignmentExpression
    | AwaitExpression
    | BinaryExpression
    | CallExpression
    | ConditionalExpression
    | FunctionExpression
    | Identifier
    | Literal
    | LogicalExpression
    | MemberExpression
    | NewExpression
    | ObjectExpression
    | UnaryExpression
    | TSAsExpression;
  consequent:
    | ArrayExpression
    | ArrowFunctionExpression
    | AssignmentExpression
    | AwaitExpression
    | BinaryExpression
    | CallExpression
    | ConditionalExpression
    | FunctionExpression
    | Identifier
    | JSXElement
    | Literal
    | LogicalExpression
    | MemberExpression
    | NewExpression
    | ObjectExpression
    | SequenceExpression
    | TemplateLiteral
    | UnaryExpression
    | YieldExpression
    | TSAsExpression
    | TSNonNullExpression
    | TSTypeAssertion;
  alternate:
    | ArrayExpression
    | ArrowFunctionExpression
    | AssignmentExpression
    | AwaitExpression
    | BinaryExpression
    | CallExpression
    | ConditionalExpression
    | FunctionExpression
    | Identifier
    | JSXElement
    | Literal
    | LogicalExpression
    | MemberExpression
    | NewExpression
    | ObjectExpression
    | SequenceExpression
    | TemplateLiteral
    | UnaryExpression
    | UpdateExpression
    | TSAsExpression
    | TSNonNullExpression
    | TSTypeAssertion;
}

export interface ContinueStatement extends BaseNode {
  type: 'ContinueStatement';
  label: null | Identifier;
}

export interface DebuggerStatement extends BaseNode {
  type: 'DebuggerStatement';
}

export interface Decorator extends BaseNode {
  type: 'Decorator';
  expression:
    | ArrowFunctionExpression
    | CallExpression
    | Identifier
    | MemberExpression
    | YieldExpression;
}

export interface DoWhileStatement extends BaseNode {
  type: 'DoWhileStatement';
  test:
    | AssignmentExpression
    | AwaitExpression
    | BinaryExpression
    | CallExpression
    | Identifier
    | Literal;
  body:
    | BlockStatement
    | BreakStatement
    | ContinueStatement
    | DoWhileStatement
    | EmptyStatement
    | VariableDeclaration
    | TSEnumDeclaration;
}

export interface EmptyStatement extends BaseNode {
  type: 'EmptyStatement';
}

export interface ExportAllDeclaration extends BaseNode {
  type: 'ExportAllDeclaration';
  source: Identifier | Literal;
}

export interface ExportDefaultDeclaration extends BaseNode {
  type: 'ExportDefaultDeclaration';
  declaration:
    | ArrowFunctionExpression
    | AssignmentExpression
    | BinaryExpression
    | CallExpression
    | ClassDeclaration
    | ClassExpression
    | FunctionDeclaration
    | FunctionExpression
    | Identifier
    | JSXElement
    | Literal
    | MemberExpression
    | NewExpression
    | ObjectExpression
    | SequenceExpression
    | UnaryExpression
    | TSAsExpression
    | TSDeclareFunction
    | TSInterfaceDeclaration;
}

export interface ExportNamedDeclaration extends BaseNode {
  type: 'ExportNamedDeclaration';
  specifiers: Array<ExportSpecifier>;
  source: null | Literal | TemplateLiteral;
  declaration:
    | null
    | ClassDeclaration
    | FunctionDeclaration
    | VariableDeclaration
    | TSDeclareFunction
    | TSEnumDeclaration
    | TSInterfaceDeclaration
    | TSModuleDeclaration
    | TSTypeAliasDeclaration;
}

export interface ExportSpecifier extends BaseNode {
  type: 'ExportSpecifier';
  local: Identifier;
  exported: Identifier;
}

export interface ExpressionStatement extends BaseNode {
  type: 'ExpressionStatement';
  directive?: string;
  expression:
    | ArrayExpression
    | ArrowFunctionExpression
    | AssignmentExpression
    | AwaitExpression
    | BinaryExpression
    | CallExpression
    | ClassExpression
    | ConditionalExpression
    | FunctionExpression
    | Identifier
    | JSXElement
    | JSXFragment
    | Literal
    | LogicalExpression
    | MemberExpression
    | MetaProperty
    | NewExpression
    | ObjectExpression
    | OptionalCallExpression
    | OptionalMemberExpression
    | SequenceExpression
    | TaggedTemplateExpression
    | TemplateLiteral
    | ThisExpression
    | UnaryExpression
    | UpdateExpression
    | YieldExpression
    | TSAsExpression
    | TSNonNullExpression;
}

export interface ForInStatement extends BaseNode {
  type: 'ForInStatement';
  right:
    | ArrayExpression
    | AwaitExpression
    | CallExpression
    | Identifier
    | Literal
    | MemberExpression
    | ObjectExpression
    | SequenceExpression
    | ThisExpression;
  left:
    | ArrayPattern
    | AssignmentPattern
    | CallExpression
    | ConditionalExpression
    | Identifier
    | MemberExpression
    | NewExpression
    | ObjectPattern
    | OptionalMemberExpression
    | ThisExpression
    | VariableDeclaration;
  body:
    | BlockStatement
    | BreakStatement
    | ContinueStatement
    | EmptyStatement
    | ExpressionStatement
    | ForInStatement
    | IfStatement
    | VariableDeclaration
    | TSEnumDeclaration;
}

export interface ForOfStatement extends BaseNode {
  type: 'ForOfStatement';
  await: boolean;
  right:
    | ArrayExpression
    | AwaitExpression
    | CallExpression
    | ConditionalExpression
    | Identifier
    | Literal
    | LogicalExpression
    | MemberExpression
    | NewExpression
    | TSAsExpression
    | TSNonNullExpression;
  left:
    | ArrayPattern
    | Identifier
    | MemberExpression
    | ObjectPattern
    | OptionalMemberExpression
    | UpdateExpression
    | VariableDeclaration;
  body:
    | BlockStatement
    | ContinueStatement
    | EmptyStatement
    | ExpressionStatement
    | ForOfStatement
    | VariableDeclaration
    | TSEnumDeclaration;
}

export interface ForStatement extends BaseNode {
  type: 'ForStatement';
  update:
    | null
    | AssignmentExpression
    | AwaitExpression
    | Identifier
    | SequenceExpression
    | UnaryExpression
    | UpdateExpression;
  test:
    | null
    | AssignmentExpression
    | AwaitExpression
    | BinaryExpression
    | Identifier
    | Literal
    | LogicalExpression
    | SequenceExpression
    | UnaryExpression;
  init:
    | null
    | AssignmentExpression
    | AwaitExpression
    | Identifier
    | SequenceExpression
    | UpdateExpression
    | VariableDeclaration;
  body:
    | BlockStatement
    | BreakStatement
    | ContinueStatement
    | EmptyStatement
    | ExpressionStatement
    | ForStatement
    | IfStatement
    | VariableDeclaration
    | TSEnumDeclaration;
}

export interface FunctionDeclaration extends BaseNode {
  type: 'FunctionDeclaration';
  generator: boolean;
  expression: boolean;
  async: boolean;
  typeParameters?: TSTypeParameterDeclaration;
  returnType?: TSTypeAnnotation;
  params: Array<
    | ArrayPattern
    | AssignmentPattern
    | Identifier
    | ObjectPattern
    | RestElement
    | TSParameterProperty
  >;
  id: null | Identifier;
  decorators?: Array<Decorator>;
  body: BlockStatement;
}

export interface FunctionExpression extends BaseNode {
  type: 'FunctionExpression';
  generator: boolean;
  expression: boolean;
  async: boolean;
  typeParameters?: TSTypeParameterDeclaration;
  returnType?: TSTypeAnnotation;
  params: Array<
    | ArrayPattern
    | AssignmentPattern
    | Identifier
    | ObjectPattern
    | RestElement
    | TSParameterProperty
  >;
  id: null | Identifier;
  body: null | BlockStatement;
}

export interface Identifier extends BaseNode {
  type: 'Identifier';
  optional?: boolean;
  name: string;
  typeAnnotation?: TSTypeAnnotation;
  decorators?: Array<Decorator>;
}

export interface IfStatement extends BaseNode {
  type: 'IfStatement';
  test:
    | AssignmentExpression
    | AwaitExpression
    | BinaryExpression
    | CallExpression
    | ConditionalExpression
    | Identifier
    | Literal
    | LogicalExpression
    | MemberExpression
    | OptionalCallExpression
    | OptionalMemberExpression
    | SequenceExpression
    | UnaryExpression
    | UpdateExpression
    | TSAsExpression;
  consequent:
    | BlockStatement
    | BreakStatement
    | ContinueStatement
    | EmptyStatement
    | ExpressionStatement
    | ForInStatement
    | ForStatement
    | LabeledStatement
    | ReturnStatement
    | ThrowStatement
    | VariableDeclaration
    | TSEnumDeclaration;
  alternate:
    | null
    | BlockStatement
    | BreakStatement
    | EmptyStatement
    | ExpressionStatement
    | ForStatement
    | IfStatement
    | ReturnStatement
    | SwitchStatement
    | VariableDeclaration
    | TSEnumDeclaration;
}

export interface Import extends BaseNode {
  type: 'Import';
}

export interface ImportDeclaration extends BaseNode {
  type: 'ImportDeclaration';
  specifiers: Array<
    ImportDefaultSpecifier | ImportNamespaceSpecifier | ImportSpecifier
  >;
  source: Literal | TemplateLiteral;
}

export interface ImportDefaultSpecifier extends BaseNode {
  type: 'ImportDefaultSpecifier';
  local: Identifier;
}

export interface ImportNamespaceSpecifier extends BaseNode {
  type: 'ImportNamespaceSpecifier';
  local: Identifier;
}

export interface ImportSpecifier extends BaseNode {
  type: 'ImportSpecifier';
  local: Identifier;
  imported: Identifier;
}

export interface JSXAttribute extends BaseNode {
  type: 'JSXAttribute';
  value: null | JSXExpressionContainer | Literal;
  name: JSXIdentifier;
}

export interface JSXClosingElement extends BaseNode {
  type: 'JSXClosingElement';
  name: JSXIdentifier;
}

export interface JSXClosingFragment extends BaseNode {
  type: 'JSXClosingFragment';
}

export interface JSXElement extends BaseNode {
  type: 'JSXElement';
  openingElement: JSXOpeningElement;
  closingElement: null | JSXClosingElement;
  children: Array<
    JSXElement | JSXExpressionContainer | JSXFragment | JSXSpreadChild | JSXText
  >;
}

export interface JSXEmptyExpression extends BaseNode {
  type: 'JSXEmptyExpression';
}

export interface JSXExpressionContainer extends BaseNode {
  type: 'JSXExpressionContainer';
  expression:
    | ArrayExpression
    | ArrowFunctionExpression
    | BinaryExpression
    | CallExpression
    | ConditionalExpression
    | FunctionExpression
    | Identifier
    | JSXElement
    | JSXEmptyExpression
    | Literal
    | MemberExpression
    | ObjectExpression
    | SequenceExpression
    | TSAsExpression;
}

export interface JSXFragment extends BaseNode {
  type: 'JSXFragment';
  openingFragment: JSXOpeningFragment;
  closingFragment: JSXClosingFragment;
  children: Array<JSXElement | JSXFragment>;
}

export interface JSXIdentifier extends BaseNode {
  type: 'JSXIdentifier';
  name: string;
}

export interface JSXMemberExpression extends BaseNode {
  type: 'JSXMemberExpression';
  property: JSXIdentifier;
  object: JSXIdentifier | JSXMemberExpression;
}

export interface JSXOpeningElement extends BaseNode {
  type: 'JSXOpeningElement';
  selfClosing: boolean;
  typeParameters?: TSTypeParameterInstantiation;
  name: JSXIdentifier | JSXMemberExpression;
  attributes: Array<JSXAttribute | JSXSpreadAttribute>;
}

export interface JSXOpeningFragment extends BaseNode {
  type: 'JSXOpeningFragment';
}

export interface JSXSpreadAttribute extends BaseNode {
  type: 'JSXSpreadAttribute';
  argument:
    | Identifier
    | MemberExpression
    | ObjectExpression
    | SequenceExpression;
}

export interface JSXSpreadChild extends BaseNode {
  type: 'JSXSpreadChild';
  expression: MemberExpression;
}

export interface JSXText extends BaseNode {
  type: 'JSXText';
  value: string;
  raw: string;
}

export interface LabeledStatement extends BaseNode {
  type: 'LabeledStatement';
  label: Identifier;
  body:
    | BlockStatement
    | BreakStatement
    | ContinueStatement
    | DoWhileStatement
    | EmptyStatement
    | ExpressionStatement
    | ForInStatement
    | ForOfStatement
    | ForStatement
    | IfStatement
    | LabeledStatement
    | TryStatement
    | VariableDeclaration
    | WhileStatement;
}

export interface Literal extends BaseNode {
  type: 'Literal';
  value: boolean | null | number | string;
  raw: string;
  regex?: {
    pattern: string;
    flags: string;
  };
}

export interface LogicalExpression extends BaseNode {
  type: 'LogicalExpression';
  operator: '&&' | '??' | '||';
  right:
    | ArrayExpression
    | ArrowFunctionExpression
    | AssignmentExpression
    | AwaitExpression
    | BinaryExpression
    | CallExpression
    | ConditionalExpression
    | FunctionExpression
    | Identifier
    | Literal
    | LogicalExpression
    | MemberExpression
    | NewExpression
    | ObjectExpression
    | SequenceExpression
    | TemplateLiteral
    | ThisExpression
    | UnaryExpression
    | TSAsExpression
    | TSNonNullExpression
    | TSTypeAssertion;
  left:
    | ArrayExpression
    | ArrowFunctionExpression
    | AssignmentExpression
    | AwaitExpression
    | BinaryExpression
    | CallExpression
    | ConditionalExpression
    | FunctionExpression
    | Identifier
    | Literal
    | LogicalExpression
    | MemberExpression
    | NewExpression
    | ObjectExpression
    | OptionalMemberExpression
    | ThisExpression
    | UnaryExpression
    | YieldExpression
    | TSAsExpression
    | TSTypeAssertion;
}

export interface MemberExpression extends BaseNode {
  type: 'MemberExpression';
  optional: boolean;
  computed: boolean;
  property:
    | ArrayExpression
    | AssignmentExpression
    | AwaitExpression
    | BinaryExpression
    | CallExpression
    | Identifier
    | Literal
    | LogicalExpression
    | MemberExpression
    | ObjectExpression
    | SequenceExpression
    | TemplateLiteral
    | UnaryExpression
    | UpdateExpression
    | TSAsExpression
    | TSNonNullExpression;
  object:
    | ArrayExpression
    | ArrowFunctionExpression
    | AssignmentExpression
    | AwaitExpression
    | BinaryExpression
    | CallExpression
    | ConditionalExpression
    | FunctionExpression
    | Identifier
    | Literal
    | LogicalExpression
    | MemberExpression
    | MetaProperty
    | NewExpression
    | ObjectExpression
    | SequenceExpression
    | Super
    | TemplateLiteral
    | ThisExpression
    | UnaryExpression
    | YieldExpression
    | TSAsExpression
    | TSNonNullExpression
    | TSTypeAssertion;
}

export interface MetaProperty extends BaseNode {
  type: 'MetaProperty';
  property: Identifier;
  meta: Identifier;
}

export interface MethodDefinition extends BaseNode {
  type: 'MethodDefinition';
  static: boolean;
  kind: 'constructor' | 'get' | 'method' | 'set';
  computed: boolean;
  accessibility?: 'private' | 'protected' | 'public';
  value: FunctionExpression;
  key:
    | ArrayExpression
    | BinaryExpression
    | CallExpression
    | ConditionalExpression
    | Identifier
    | Literal
    | MemberExpression
    | MetaProperty
    | ObjectExpression
    | SequenceExpression
    | YieldExpression;
  decorators?: Array<Decorator>;
}

export interface NewExpression extends BaseNode {
  type: 'NewExpression';
  typeParameters?: TSTypeParameterInstantiation;
  callee:
    | ArrayExpression
    | AwaitExpression
    | BinaryExpression
    | CallExpression
    | ClassExpression
    | ConditionalExpression
    | Identifier
    | LogicalExpression
    | MemberExpression
    | NewExpression
    | TSAsExpression;
  arguments: Array<
    | ArrayExpression
    | ArrowFunctionExpression
    | AwaitExpression
    | BinaryExpression
    | CallExpression
    | ConditionalExpression
    | FunctionExpression
    | Identifier
    | Literal
    | LogicalExpression
    | MemberExpression
    | NewExpression
    | ObjectExpression
    | SpreadElement
    | TemplateLiteral
    | ThisExpression
    | UnaryExpression
    | TSAsExpression
    | TSNonNullExpression
    | TSTypeAssertion
  >;
}

export interface ObjectExpression extends BaseNode {
  type: 'ObjectExpression';
  properties: Array<Property | SpreadElement>;
}

export interface ObjectPattern extends BaseNode {
  type: 'ObjectPattern';
  optional?: boolean;
  typeAnnotation?: TSTypeAnnotation;
  properties: Array<Property | RestElement>;
}

export interface OptionalCallExpression extends BaseNode {
  type: 'OptionalCallExpression';
  optional: boolean;
  callee:
    | CallExpression
    | Identifier
    | MemberExpression
    | OptionalMemberExpression;
  arguments: Array<
    | AssignmentExpression
    | Identifier
    | Literal
    | ObjectExpression
    | SpreadElement
  >;
}

export interface OptionalMemberExpression extends BaseNode {
  type: 'OptionalMemberExpression';
  optional: boolean;
  computed: boolean;
  property: AssignmentExpression | Identifier | Literal;
  object:
    | CallExpression
    | Identifier
    | MemberExpression
    | OptionalCallExpression
    | OptionalMemberExpression;
}

export interface Program extends BaseNode {
  type: 'Program';
  sourceType: 'module' | 'script';
  body: Array<
    | BlockStatement
    | BreakStatement
    | ClassDeclaration
    | ContinueStatement
    | DebuggerStatement
    | DoWhileStatement
    | EmptyStatement
    | ExportAllDeclaration
    | ExportDefaultDeclaration
    | ExportNamedDeclaration
    | ExpressionStatement
    | ForInStatement
    | ForOfStatement
    | ForStatement
    | FunctionDeclaration
    | IfStatement
    | ImportDeclaration
    | LabeledStatement
    | ReturnStatement
    | SwitchStatement
    | ThrowStatement
    | TryStatement
    | VariableDeclaration
    | WhileStatement
    | WithStatement
    | TSDeclareFunction
    | TSEnumDeclaration
    | TSExportAssignment
    | TSImportEqualsDeclaration
    | TSInterfaceDeclaration
    | TSModuleDeclaration
    | TSNamespaceExportDeclaration
    | TSTypeAliasDeclaration
  >;
}

export interface Property extends BaseNode {
  type: 'Property';
  shorthand: boolean;
  method: boolean;
  kind: 'get' | 'init' | 'set';
  computed: boolean;
  value:
    | ArrayExpression
    | ArrayPattern
    | ArrowFunctionExpression
    | AssignmentExpression
    | AssignmentPattern
    | AwaitExpression
    | BinaryExpression
    | CallExpression
    | ClassExpression
    | ConditionalExpression
    | FunctionExpression
    | Identifier
    | Literal
    | LogicalExpression
    | MemberExpression
    | MetaProperty
    | NewExpression
    | ObjectExpression
    | ObjectPattern
    | OptionalCallExpression
    | OptionalMemberExpression
    | TaggedTemplateExpression
    | TemplateLiteral
    | ThisExpression
    | UnaryExpression
    | UpdateExpression
    | TSAsExpression
    | TSNonNullExpression
    | TSTypeAssertion;
  key:
    | ArrayExpression
    | AwaitExpression
    | BinaryExpression
    | CallExpression
    | Identifier
    | Literal
    | LogicalExpression
    | MemberExpression
    | MetaProperty
    | ObjectExpression
    | SequenceExpression
    | TemplateLiteral
    | UnaryExpression
    | YieldExpression;
}

export interface RestElement extends BaseNode {
  type: 'RestElement';
  optional?: boolean;
  typeAnnotation?: TSTypeAnnotation;
  argument: ArrayPattern | Identifier | OptionalMemberExpression;
}

export interface ReturnStatement extends BaseNode {
  type: 'ReturnStatement';
  argument:
    | null
    | ArrayExpression
    | ArrowFunctionExpression
    | AssignmentExpression
    | AwaitExpression
    | BinaryExpression
    | CallExpression
    | ClassExpression
    | ConditionalExpression
    | FunctionExpression
    | Identifier
    | JSXElement
    | JSXFragment
    | Literal
    | LogicalExpression
    | MemberExpression
    | MetaProperty
    | NewExpression
    | ObjectExpression
    | OptionalCallExpression
    | SequenceExpression
    | TemplateLiteral
    | ThisExpression
    | UnaryExpression
    | YieldExpression
    | TSAsExpression
    | TSNonNullExpression
    | TSTypeAssertion;
}

export interface SequenceExpression extends BaseNode {
  type: 'SequenceExpression';
  expressions: Array<
    | ArrayExpression
    | ArrowFunctionExpression
    | AssignmentExpression
    | AwaitExpression
    | BinaryExpression
    | CallExpression
    | ConditionalExpression
    | FunctionExpression
    | Identifier
    | Literal
    | LogicalExpression
    | MemberExpression
    | NewExpression
    | ObjectExpression
    | SequenceExpression
    | ThisExpression
    | UnaryExpression
    | UpdateExpression
    | YieldExpression
  >;
}

export interface SpreadElement extends BaseNode {
  type: 'SpreadElement';
  argument:
    | ArrayExpression
    | AwaitExpression
    | BinaryExpression
    | CallExpression
    | ConditionalExpression
    | FunctionExpression
    | Identifier
    | Literal
    | LogicalExpression
    | MemberExpression
    | NewExpression
    | ObjectExpression
    | TSAsExpression
    | TSNonNullExpression
    | TSTypeAssertion;
}

export interface Super extends BaseNode {
  type: 'Super';
}

export interface SwitchCase extends BaseNode {
  type: 'SwitchCase';
  test:
    | null
    | AwaitExpression
    | CallExpression
    | Identifier
    | Literal
    | MemberExpression
    | SequenceExpression
    | TemplateLiteral
    | UnaryExpression;
  consequent: Array<
    | BlockStatement
    | BreakStatement
    | ContinueStatement
    | ExpressionStatement
    | ForInStatement
    | ForOfStatement
    | ForStatement
    | FunctionDeclaration
    | IfStatement
    | ReturnStatement
    | SwitchStatement
    | ThrowStatement
    | TryStatement
    | VariableDeclaration
    | WhileStatement
    | WithStatement
  >;
}

export interface SwitchStatement extends BaseNode {
  type: 'SwitchStatement';
  discriminant:
    | AwaitExpression
    | BinaryExpression
    | CallExpression
    | ConditionalExpression
    | Identifier
    | Literal
    | LogicalExpression
    | MemberExpression
    | OptionalMemberExpression
    | UnaryExpression;
  cases: Array<SwitchCase>;
}

export interface TaggedTemplateExpression extends BaseNode {
  type: 'TaggedTemplateExpression';
  typeParameters?: TSTypeParameterInstantiation;
  tag: Identifier | MemberExpression;
  quasi: TemplateLiteral;
}

export interface TemplateElement extends BaseNode {
  type: 'TemplateElement';
  tail: boolean;
  value: {
    raw: string;
    cooked: string;
  };
}

export interface TemplateLiteral extends BaseNode {
  type: 'TemplateLiteral';
  quasis: Array<TemplateElement>;
  expressions: Array<
    | ArrowFunctionExpression
    | BinaryExpression
    | CallExpression
    | ConditionalExpression
    | Identifier
    | Literal
    | LogicalExpression
    | MemberExpression
    | UnaryExpression
    | TSAsExpression
  >;
}

export interface ThisExpression extends BaseNode {
  type: 'ThisExpression';
}

export interface ThrowStatement extends BaseNode {
  type: 'ThrowStatement';
  argument:
    | ArrayExpression
    | CallExpression
    | Identifier
    | Literal
    | MemberExpression
    | NewExpression
    | ObjectExpression;
}

export interface TryStatement extends BaseNode {
  type: 'TryStatement';
  handler: null | CatchClause;
  finalizer: null | BlockStatement;
  block: BlockStatement;
}

export interface UnaryExpression extends BaseNode {
  type: 'UnaryExpression';
  prefix: boolean;
  operator: '!' | '+' | '-' | 'delete' | 'typeof' | 'void' | '~';
  argument:
    | ArrowFunctionExpression
    | AssignmentExpression
    | AwaitExpression
    | BigIntLiteral
    | BinaryExpression
    | CallExpression
    | ClassExpression
    | ConditionalExpression
    | FunctionExpression
    | Identifier
    | Literal
    | LogicalExpression
    | MemberExpression
    | NewExpression
    | ObjectExpression
    | OptionalCallExpression
    | OptionalMemberExpression
    | SequenceExpression
    | TemplateLiteral
    | ThisExpression
    | UnaryExpression
    | UpdateExpression
    | YieldExpression
    | TSNonNullExpression;
}

export interface UpdateExpression extends BaseNode {
  type: 'UpdateExpression';
  prefix: boolean;
  operator: '++' | '--';
  argument:
    | ArrayExpression
    | BinaryExpression
    | CallExpression
    | ConditionalExpression
    | FunctionExpression
    | Identifier
    | Literal
    | MemberExpression
    | NewExpression
    | ObjectExpression
    | OptionalMemberExpression
    | ThisExpression
    | TSNonNullExpression;
}

export interface VariableDeclaration extends BaseNode {
  type: 'VariableDeclaration';
  kind: 'const' | 'let' | 'var';
  declare?: boolean;
  decorators?: Array<Decorator>;
  declarations: Array<VariableDeclarator>;
}

export interface VariableDeclarator extends BaseNode {
  type: 'VariableDeclarator';
  definite?: boolean;
  init:
    | null
    | ArrayExpression
    | ArrowFunctionExpression
    | AssignmentExpression
    | AwaitExpression
    | BigIntLiteral
    | BinaryExpression
    | CallExpression
    | ClassExpression
    | ConditionalExpression
    | FunctionExpression
    | Identifier
    | JSXElement
    | Literal
    | LogicalExpression
    | MemberExpression
    | MetaProperty
    | NewExpression
    | ObjectExpression
    | OptionalCallExpression
    | OptionalMemberExpression
    | SequenceExpression
    | TaggedTemplateExpression
    | TemplateLiteral
    | ThisExpression
    | UnaryExpression
    | UpdateExpression
    | YieldExpression
    | TSAsExpression
    | TSNonNullExpression
    | TSTypeAssertion;
  id: ArrayPattern | Identifier | ObjectPattern;
}

export interface WhileStatement extends BaseNode {
  type: 'WhileStatement';
  test:
    | AssignmentExpression
    | AwaitExpression
    | BinaryExpression
    | CallExpression
    | Identifier
    | Literal
    | LogicalExpression
    | MemberExpression
    | UnaryExpression;
  body:
    | BlockStatement
    | BreakStatement
    | ContinueStatement
    | EmptyStatement
    | ExpressionStatement
    | LabeledStatement
    | TryStatement
    | VariableDeclaration
    | TSEnumDeclaration;
}

export interface WithStatement extends BaseNode {
  type: 'WithStatement';
  object: AwaitExpression | Identifier | Literal | ObjectExpression;
  body:
    | BlockStatement
    | EmptyStatement
    | ReturnStatement
    | VariableDeclaration
    | TSEnumDeclaration;
}

export interface YieldExpression extends BaseNode {
  type: 'YieldExpression';
  delegate: boolean;
  argument:
    | null
    | ArrayExpression
    | ArrowFunctionExpression
    | AssignmentExpression
    | AwaitExpression
    | BinaryExpression
    | CallExpression
    | ConditionalExpression
    | Identifier
    | Literal
    | MemberExpression
    | NewExpression
    | ObjectExpression
    | ThisExpression
    | YieldExpression
    | TSAsExpression;
}

export interface TSAbstractClassProperty extends BaseNode {
  type: 'TSAbstractClassProperty';
  static: boolean;
  readonly?: boolean;
  definite?: boolean;
  declare: boolean;
  computed: boolean;
  accessibility?: 'private' | 'protected' | 'public';
  value: null | Literal;
  typeAnnotation?: TSTypeAnnotation;
  key: Identifier;
}

export interface TSAbstractMethodDefinition extends BaseNode {
  type: 'TSAbstractMethodDefinition';
  static: boolean;
  kind: 'constructor' | 'get' | 'method' | 'set';
  computed: boolean;
  accessibility?: 'private' | 'protected' | 'public';
  value: FunctionExpression;
  key: Identifier;
}

export interface TSArrayType extends BaseNode {
  type: 'TSArrayType';
  elementType:
    | TSArrayType
    | TSIndexedAccessType
    | TSLiteralType
    | TSMappedType
    | TSParenthesizedType
    | TSThisType
    | TSTupleType
    | TSTypeLiteral
    | TSTypeQuery
    | TSTypeReference
    | TSAnyKeyword
    | TSBigIntKeyword
    | TSBooleanKeyword
    | TSNeverKeyword
    | TSNullKeyword
    | TSNumberKeyword
    | TSStringKeyword
    | TSSymbolKeyword
    | TSUndefinedKeyword
    | TSUnknownKeyword
    | TSVoidKeyword;
}

export interface TSAsExpression extends BaseNode {
  type: 'TSAsExpression';
  typeAnnotation:
    | TSArrayType
    | TSConstructorType
    | TSFunctionType
    | TSImportType
    | TSIndexedAccessType
    | TSIntersectionType
    | TSLiteralType
    | TSParenthesizedType
    | TSTupleType
    | TSTypeLiteral
    | TSTypeOperator
    | TSTypeQuery
    | TSTypeReference
    | TSUnionType
    | TSAnyKeyword
    | TSBooleanKeyword
    | TSNeverKeyword
    | TSNumberKeyword
    | TSStringKeyword
    | TSUnknownKeyword;
  expression:
    | ArrayExpression
    | ArrowFunctionExpression
    | BinaryExpression
    | CallExpression
    | ClassExpression
    | ConditionalExpression
    | FunctionExpression
    | Identifier
    | Literal
    | LogicalExpression
    | MemberExpression
    | NewExpression
    | ObjectExpression
    | OptionalMemberExpression
    | TaggedTemplateExpression
    | TemplateLiteral
    | ThisExpression
    | TSAsExpression
    | TSNonNullExpression;
}

export interface TSCallSignatureDeclaration extends BaseNode {
  type: 'TSCallSignatureDeclaration';
  typeParameters?: TSTypeParameterDeclaration;
  returnType?: TSTypeAnnotation;
  params: Array<AssignmentPattern | Identifier | ObjectPattern | RestElement>;
}

export interface TSClassImplements extends BaseNode {
  type: 'TSClassImplements';
  typeParameters?: TSTypeParameterInstantiation;
  expression: Identifier | MemberExpression;
}

export interface TSConditionalType extends BaseNode {
  type: 'TSConditionalType';
  trueType:
    | TSConditionalType
    | TSFunctionType
    | TSImportType
    | TSIndexedAccessType
    | TSInferType
    | TSLiteralType
    | TSMappedType
    | TSParenthesizedType
    | TSTupleType
    | TSTypeLiteral
    | TSTypeOperator
    | TSTypeReference
    | TSUnionType
    | TSAnyKeyword
    | TSBooleanKeyword
    | TSNeverKeyword
    | TSNumberKeyword
    | TSStringKeyword
    | TSUnknownKeyword;
  falseType:
    | TSArrayType
    | TSConditionalType
    | TSFunctionType
    | TSIndexedAccessType
    | TSInferType
    | TSIntersectionType
    | TSLiteralType
    | TSMappedType
    | TSParenthesizedType
    | TSTupleType
    | TSTypeLiteral
    | TSTypeQuery
    | TSTypeReference
    | TSAnyKeyword
    | TSBooleanKeyword
    | TSNeverKeyword
    | TSNumberKeyword
    | TSStringKeyword
    | TSUndefinedKeyword
    | TSUnknownKeyword;
  extendsType:
    | TSArrayType
    | TSConstructorType
    | TSFunctionType
    | TSIndexedAccessType
    | TSInferType
    | TSLiteralType
    | TSMappedType
    | TSParenthesizedType
    | TSTupleType
    | TSTypeLiteral
    | TSTypeOperator
    | TSTypeReference
    | TSUnionType
    | TSAnyKeyword
    | TSBooleanKeyword
    | TSNullKeyword
    | TSNumberKeyword
    | TSObjectKeyword
    | TSStringKeyword
    | TSUnknownKeyword
    | TSVoidKeyword;
  checkType:
    | TSIndexedAccessType
    | TSInferType
    | TSParenthesizedType
    | TSTupleType
    | TSTypeLiteral
    | TSTypeQuery
    | TSTypeReference
    | TSAnyKeyword
    | TSNullKeyword
    | TSNumberKeyword
    | TSStringKeyword
    | TSUndefinedKeyword
    | TSUnknownKeyword;
}

export interface TSConstructSignatureDeclaration extends BaseNode {
  type: 'TSConstructSignatureDeclaration';
  typeParameters?: TSTypeParameterDeclaration;
  returnType?: TSTypeAnnotation;
  params: Array<Identifier | ObjectPattern | RestElement | TSParameterProperty>;
}

export interface TSConstructorType extends BaseNode {
  type: 'TSConstructorType';
  typeParameters?: TSTypeParameterDeclaration;
  returnType: TSTypeAnnotation;
  params: Array<ArrayPattern | Identifier | RestElement>;
}

export interface TSDeclareFunction extends BaseNode {
  type: 'TSDeclareFunction';
  generator: boolean;
  expression: boolean;
  declare?: boolean;
  async: boolean;
  typeParameters?: TSTypeParameterDeclaration;
  returnType?: TSTypeAnnotation;
  params: Array<
    ArrayPattern | AssignmentPattern | Identifier | ObjectPattern | RestElement
  >;
  id: null | Identifier;
  body?: BlockStatement;
}

export interface TSEnumDeclaration extends BaseNode {
  type: 'TSEnumDeclaration';
  declare?: boolean;
  const?: boolean;
  modifiers?: Array<
    TSAsyncKeyword | TSPrivateKeyword | TSPublicKeyword | TSStaticKeyword
  >;
  members: Array<TSEnumMember>;
  id: Identifier;
  decorators?: Array<Decorator>;
}

export interface TSEnumMember extends BaseNode {
  type: 'TSEnumMember';
  computed?: boolean;
  initializer?:
    | AssignmentExpression
    | AwaitExpression
    | BinaryExpression
    | CallExpression
    | Identifier
    | Literal
    | MemberExpression
    | TemplateLiteral
    | UnaryExpression
    | UpdateExpression
    | YieldExpression;
  id: Identifier | Literal;
}

export interface TSExportAssignment extends BaseNode {
  type: 'TSExportAssignment';
  expression:
    | BinaryExpression
    | CallExpression
    | ClassExpression
    | FunctionExpression
    | Identifier
    | Literal
    | MemberExpression
    | NewExpression
    | ObjectExpression
    | UnaryExpression;
}

export interface TSExternalModuleReference extends BaseNode {
  type: 'TSExternalModuleReference';
  expression: Identifier | Literal;
}

export interface TSFunctionType extends BaseNode {
  type: 'TSFunctionType';
  typeParameters?: TSTypeParameterDeclaration;
  returnType: TSTypeAnnotation;
  params: Array<
    | ArrayPattern
    | AssignmentPattern
    | Identifier
    | ObjectPattern
    | RestElement
    | TSParameterProperty
  >;
}

export interface TSImportEqualsDeclaration extends BaseNode {
  type: 'TSImportEqualsDeclaration';
  isExport: boolean;
  moduleReference: Identifier | TSExternalModuleReference | TSQualifiedName;
  id: Identifier;
}

export interface TSImportType extends BaseNode {
  type: 'TSImportType';
  isTypeOf: boolean;
  typeParameters: null | TSTypeParameterInstantiation;
  qualifier: null | Identifier | TSQualifiedName;
  parameter: TSImportType | TSLiteralType | TSTypeLiteral | TSTypeReference;
}

export interface TSIndexSignature extends BaseNode {
  type: 'TSIndexSignature';
  static?: boolean;
  readonly?: boolean;
  export?: boolean;
  accessibility?: 'private' | 'public';
  typeAnnotation?: TSTypeAnnotation;
  parameters: Array<
    AssignmentPattern | Identifier | RestElement | TSParameterProperty
  >;
}

export interface TSIndexedAccessType extends BaseNode {
  type: 'TSIndexedAccessType';
  objectType:
    | TSArrayType
    | TSImportType
    | TSIndexedAccessType
    | TSMappedType
    | TSParenthesizedType
    | TSThisType
    | TSTupleType
    | TSTypeLiteral
    | TSTypeReference
    | TSAnyKeyword;
  indexType:
    | TSConditionalType
    | TSIndexedAccessType
    | TSIntersectionType
    | TSLiteralType
    | TSTupleType
    | TSTypeLiteral
    | TSTypeOperator
    | TSTypeQuery
    | TSTypeReference
    | TSUnionType
    | TSAnyKeyword
    | TSBooleanKeyword
    | TSNeverKeyword
    | TSNumberKeyword
    | TSStringKeyword
    | TSUndefinedKeyword
    | TSVoidKeyword;
}

export interface TSInferType extends BaseNode {
  type: 'TSInferType';
  typeParameter: TSTypeParameter;
}

export interface TSInterfaceBody extends BaseNode {
  type: 'TSInterfaceBody';
  body: Array<
    | TSCallSignatureDeclaration
    | TSConstructSignatureDeclaration
    | TSIndexSignature
    | TSMethodSignature
    | TSPropertySignature
  >;
}

export interface TSInterfaceDeclaration extends BaseNode {
  type: 'TSInterfaceDeclaration';
  declare?: boolean;
  abstract?: boolean;
  typeParameters?: TSTypeParameterDeclaration;
  implements?: Array<TSInterfaceHeritage>;
  id: Identifier;
  extends?: Array<TSInterfaceHeritage>;
  decorators?: Array<Decorator>;
  body: TSInterfaceBody;
}

export interface TSInterfaceHeritage extends BaseNode {
  type: 'TSInterfaceHeritage';
  typeParameters?: TSTypeParameterInstantiation;
  expression: CallExpression | Identifier | MemberExpression | UnaryExpression;
}

export interface TSIntersectionType extends BaseNode {
  type: 'TSIntersectionType';
  types: Array<
    | TSArrayType
    | TSImportType
    | TSIndexedAccessType
    | TSLiteralType
    | TSMappedType
    | TSParenthesizedType
    | TSThisType
    | TSTupleType
    | TSTypeLiteral
    | TSTypeOperator
    | TSTypeQuery
    | TSTypeReference
    | TSAnyKeyword
    | TSBooleanKeyword
    | TSNeverKeyword
    | TSNullKeyword
    | TSNumberKeyword
    | TSObjectKeyword
    | TSStringKeyword
    | TSSymbolKeyword
    | TSUndefinedKeyword
    | TSVoidKeyword
  >;
}

export interface TSLiteralType extends BaseNode {
  type: 'TSLiteralType';
  literal: BigIntLiteral | Literal | TemplateLiteral | UnaryExpression;
}

export interface TSMappedType extends BaseNode {
  type: 'TSMappedType';
  readonly?: boolean | '+' | '-';
  optional?: boolean | '+' | '-';
  typeParameter: TSTypeParameter;
  typeAnnotation?:
    | TSArrayType
    | TSConditionalType
    | TSFunctionType
    | TSIndexedAccessType
    | TSLiteralType
    | TSTupleType
    | TSTypeLiteral
    | TSTypeReference
    | TSUnionType
    | TSAnyKeyword
    | TSNeverKeyword
    | TSNumberKeyword
    | TSStringKeyword
    | TSVoidKeyword;
}

export interface TSMethodSignature extends BaseNode {
  type: 'TSMethodSignature';
  optional?: boolean;
  computed: boolean;
  typeParameters?: TSTypeParameterDeclaration;
  returnType?: TSTypeAnnotation;
  params: Array<
    ArrayPattern | AssignmentPattern | Identifier | ObjectPattern | RestElement
  >;
  key:
    | BinaryExpression
    | CallExpression
    | Identifier
    | Literal
    | MemberExpression;
}

export interface TSModuleBlock extends BaseNode {
  type: 'TSModuleBlock';
  body: Array<
    | BlockStatement
    | BreakStatement
    | ClassDeclaration
    | ContinueStatement
    | DebuggerStatement
    | DoWhileStatement
    | EmptyStatement
    | ExportAllDeclaration
    | ExportDefaultDeclaration
    | ExportNamedDeclaration
    | ExpressionStatement
    | ForInStatement
    | ForOfStatement
    | ForStatement
    | FunctionDeclaration
    | IfStatement
    | ImportDeclaration
    | LabeledStatement
    | ReturnStatement
    | SwitchStatement
    | ThrowStatement
    | TryStatement
    | VariableDeclaration
    | WhileStatement
    | WithStatement
    | TSDeclareFunction
    | TSEnumDeclaration
    | TSExportAssignment
    | TSImportEqualsDeclaration
    | TSInterfaceDeclaration
    | TSModuleDeclaration
    | TSTypeAliasDeclaration
  >;
}

export interface TSModuleDeclaration extends BaseNode {
  type: 'TSModuleDeclaration';
  global?: boolean;
  declare?: boolean;
  modifiers?: Array<
    TSAsyncKeyword | TSPrivateKeyword | TSPublicKeyword | TSStaticKeyword
  >;
  id: Identifier | Literal;
  body?: TSModuleBlock | TSModuleDeclaration;
}

export interface TSNamespaceExportDeclaration extends BaseNode {
  type: 'TSNamespaceExportDeclaration';
  id: Identifier;
}

export interface TSNonNullExpression extends BaseNode {
  type: 'TSNonNullExpression';
  expression:
    | CallExpression
    | Identifier
    | Literal
    | LogicalExpression
    | MemberExpression;
}

export interface TSOptionalType extends BaseNode {
  type: 'TSOptionalType';
  typeAnnotation:
    | TSArrayType
    | TSAnyKeyword
    | TSBooleanKeyword
    | TSNumberKeyword
    | TSStringKeyword;
}

export interface TSParameterProperty extends BaseNode {
  type: 'TSParameterProperty';
  static?: boolean;
  readonly?: boolean;
  export?: boolean;
  accessibility?: 'private' | 'protected' | 'public';
  parameter:
    | ArrayPattern
    | AssignmentPattern
    | Identifier
    | ObjectPattern
    | RestElement;
}

export interface TSParenthesizedType extends BaseNode {
  type: 'TSParenthesizedType';
  typeAnnotation:
    | TSArrayType
    | TSConditionalType
    | TSConstructorType
    | TSFunctionType
    | TSImportType
    | TSIndexedAccessType
    | TSInferType
    | TSIntersectionType
    | TSMappedType
    | TSParenthesizedType
    | TSThisType
    | TSTupleType
    | TSTypeLiteral
    | TSTypeOperator
    | TSTypeQuery
    | TSTypeReference
    | TSUnionType
    | TSNumberKeyword
    | TSStringKeyword;
}

export interface TSPropertySignature extends BaseNode {
  type: 'TSPropertySignature';
  readonly?: boolean;
  optional?: boolean;
  computed: boolean;
  accessibility?: 'private' | 'protected' | 'public';
  typeAnnotation?: TSTypeAnnotation;
  static?: unknown;
  key:
    | AssignmentExpression
    | Identifier
    | Literal
    | MemberExpression
    | UnaryExpression;
  initializer?: Literal;
  export?: unknown;
}

export interface TSQualifiedName extends BaseNode {
  type: 'TSQualifiedName';
  right: Identifier;
  left: Identifier | TSQualifiedName;
}

export interface TSRestType extends BaseNode {
  type: 'TSRestType';
  typeAnnotation: TSArrayType;
}

export interface TSThisType extends BaseNode {
  type: 'TSThisType';
}

export interface TSTupleType extends BaseNode {
  type: 'TSTupleType';
  elementTypes: Array<
    | TSArrayType
    | TSConstructorType
    | TSFunctionType
    | TSIndexedAccessType
    | TSInferType
    | TSIntersectionType
    | TSLiteralType
    | TSOptionalType
    | TSParenthesizedType
    | TSRestType
    | TSThisType
    | TSTupleType
    | TSTypeLiteral
    | TSTypeOperator
    | TSTypeReference
    | TSUnionType
    | TSAnyKeyword
    | TSBigIntKeyword
    | TSBooleanKeyword
    | TSNumberKeyword
    | TSStringKeyword
    | TSUndefinedKeyword
  >;
}

export interface TSTypeAliasDeclaration extends BaseNode {
  type: 'TSTypeAliasDeclaration';
  declare?: boolean;
  typeParameters?: TSTypeParameterDeclaration;
  typeAnnotation:
    | TSArrayType
    | TSConditionalType
    | TSConstructorType
    | TSFunctionType
    | TSImportType
    | TSIndexedAccessType
    | TSInferType
    | TSIntersectionType
    | TSLiteralType
    | TSMappedType
    | TSParenthesizedType
    | TSTupleType
    | TSTypeLiteral
    | TSTypeOperator
    | TSTypeQuery
    | TSTypeReference
    | TSUnionType
    | TSAnyKeyword
    | TSBooleanKeyword
    | TSNeverKeyword
    | TSNumberKeyword
    | TSStringKeyword
    | TSUndefinedKeyword
    | TSVoidKeyword;
  id: Identifier;
}

export interface TSTypeAnnotation extends BaseNode {
  type: 'TSTypeAnnotation';
  typeAnnotation:
    | TSArrayType
    | TSConditionalType
    | TSConstructorType
    | TSFunctionType
    | TSImportType
    | TSIndexedAccessType
    | TSInferType
    | TSIntersectionType
    | TSLiteralType
    | TSMappedType
    | TSParenthesizedType
    | TSThisType
    | TSTupleType
    | TSTypeLiteral
    | TSTypeOperator
    | TSTypePredicate
    | TSTypeQuery
    | TSTypeReference
    | TSUnionType
    | TSAnyKeyword
    | TSBigIntKeyword
    | TSBooleanKeyword
    | TSNeverKeyword
    | TSNullKeyword
    | TSNumberKeyword
    | TSObjectKeyword
    | TSStringKeyword
    | TSSymbolKeyword
    | TSUndefinedKeyword
    | TSUnknownKeyword
    | TSVoidKeyword;
}

export interface TSTypeAssertion extends BaseNode {
  type: 'TSTypeAssertion';
  typeAnnotation:
    | TSArrayType
    | TSIntersectionType
    | TSTupleType
    | TSTypeOperator
    | TSTypeReference
    | TSUnionType
    | TSAnyKeyword
    | TSStringKeyword;
  expression:
    | ArrayExpression
    | ArrowFunctionExpression
    | CallExpression
    | ConditionalExpression
    | FunctionExpression
    | Identifier
    | Literal
    | MemberExpression
    | NewExpression
    | ObjectExpression
    | TSTypeAssertion;
}

export interface TSTypeLiteral extends BaseNode {
  type: 'TSTypeLiteral';
  members: Array<
    | TSCallSignatureDeclaration
    | TSConstructSignatureDeclaration
    | TSIndexSignature
    | TSMethodSignature
    | TSPropertySignature
  >;
}

export interface TSTypeOperator extends BaseNode {
  type: 'TSTypeOperator';
  operator: 'keyof' | 'readonly' | 'unique';
  typeAnnotation:
    | TSArrayType
    | TSIndexedAccessType
    | TSParenthesizedType
    | TSThisType
    | TSTupleType
    | TSTypeLiteral
    | TSTypeOperator
    | TSTypeQuery
    | TSTypeReference
    | TSAnyKeyword
    | TSBooleanKeyword
    | TSNeverKeyword
    | TSNullKeyword
    | TSNumberKeyword
    | TSStringKeyword
    | TSSymbolKeyword
    | TSUndefinedKeyword
    | TSUnknownKeyword
    | TSVoidKeyword;
}

export interface TSTypeParameter extends BaseNode {
  type: 'TSTypeParameter';
  name: Identifier;
  default?:
    | TSConditionalType
    | TSIndexedAccessType
    | TSLiteralType
    | TSTypeLiteral
    | TSTypeOperator
    | TSTypeReference
    | TSAnyKeyword
    | TSNeverKeyword
    | TSNumberKeyword
    | TSObjectKeyword
    | TSStringKeyword
    | TSUndefinedKeyword
    | TSUnknownKeyword;
  constraint?:
    | TSArrayType
    | TSConstructorType
    | TSFunctionType
    | TSIndexedAccessType
    | TSIntersectionType
    | TSLiteralType
    | TSMappedType
    | TSParenthesizedType
    | TSTupleType
    | TSTypeLiteral
    | TSTypeOperator
    | TSTypeQuery
    | TSTypeReference
    | TSUnionType
    | TSAnyKeyword
    | TSNeverKeyword
    | TSNullKeyword
    | TSNumberKeyword
    | TSObjectKeyword
    | TSStringKeyword
    | TSUndefinedKeyword
    | TSUnknownKeyword
    | TSVoidKeyword;
}

export interface TSTypeParameterDeclaration extends BaseNode {
  type: 'TSTypeParameterDeclaration';
  params: Array<TSTypeParameter>;
}

export interface TSTypeParameterInstantiation extends BaseNode {
  type: 'TSTypeParameterInstantiation';
  params: Array<
    | TSArrayType
    | TSConditionalType
    | TSConstructorType
    | TSFunctionType
    | TSImportType
    | TSIndexedAccessType
    | TSInferType
    | TSIntersectionType
    | TSLiteralType
    | TSMappedType
    | TSParenthesizedType
    | TSThisType
    | TSTupleType
    | TSTypeLiteral
    | TSTypeOperator
    | TSTypeQuery
    | TSTypeReference
    | TSUnionType
    | TSAnyKeyword
    | TSBigIntKeyword
    | TSBooleanKeyword
    | TSNeverKeyword
    | TSNullKeyword
    | TSNumberKeyword
    | TSObjectKeyword
    | TSStringKeyword
    | TSSymbolKeyword
    | TSUndefinedKeyword
    | TSUnknownKeyword
    | TSVoidKeyword
  >;
}

export interface TSTypePredicate extends BaseNode {
  type: 'TSTypePredicate';
  asserts: boolean;
  typeAnnotation: null | TSTypeAnnotation;
  parameterName: Identifier | TSThisType;
}

export interface TSTypeQuery extends BaseNode {
  type: 'TSTypeQuery';
  exprName: Identifier | TSQualifiedName;
}

export interface TSTypeReference extends BaseNode {
  type: 'TSTypeReference';
  typeParameters?: TSTypeParameterInstantiation;
  typeName: Identifier | TSQualifiedName;
}

export interface TSUnionType extends BaseNode {
  type: 'TSUnionType';
  types: Array<
    | TSArrayType
    | TSImportType
    | TSIndexedAccessType
    | TSIntersectionType
    | TSLiteralType
    | TSParenthesizedType
    | TSThisType
    | TSTupleType
    | TSTypeLiteral
    | TSTypeOperator
    | TSTypeQuery
    | TSTypeReference
    | TSAnyKeyword
    | TSBigIntKeyword
    | TSBooleanKeyword
    | TSNeverKeyword
    | TSNullKeyword
    | TSNumberKeyword
    | TSObjectKeyword
    | TSStringKeyword
    | TSSymbolKeyword
    | TSUndefinedKeyword
    | TSUnknownKeyword
    | TSVoidKeyword
  >;
}

export interface TSAnyKeyword extends BaseNode {
  type: 'TSAnyKeyword';
}

export interface TSAsyncKeyword extends BaseNode {
  type: 'TSAsyncKeyword';
  transformFlags: number;
}

export interface TSBigIntKeyword extends BaseNode {
  type: 'TSBigIntKeyword';
}

export interface TSBooleanKeyword extends BaseNode {
  type: 'TSBooleanKeyword';
}

export interface TSNeverKeyword extends BaseNode {
  type: 'TSNeverKeyword';
}

export interface TSNullKeyword extends BaseNode {
  type: 'TSNullKeyword';
}

export interface TSNumberKeyword extends BaseNode {
  type: 'TSNumberKeyword';
}

export interface TSObjectKeyword extends BaseNode {
  type: 'TSObjectKeyword';
}

export interface TSPrivateKeyword extends BaseNode {
  type: 'TSPrivateKeyword';
  transformFlags: number;
}

export interface TSPublicKeyword extends BaseNode {
  type: 'TSPublicKeyword';
  transformFlags: number;
}

export interface TSStaticKeyword extends BaseNode {
  type: 'TSStaticKeyword';
  transformFlags: number;
}

export interface TSStringKeyword extends BaseNode {
  type: 'TSStringKeyword';
}

export interface TSSymbolKeyword extends BaseNode {
  type: 'TSSymbolKeyword';
}

export interface TSUndefinedKeyword extends BaseNode {
  type: 'TSUndefinedKeyword';
}

export interface TSUnknownKeyword extends BaseNode {
  type: 'TSUnknownKeyword';
}

export interface TSVoidKeyword extends BaseNode {
  type: 'TSVoidKeyword';
}
