const template = `// This file is autogenerated, do not modify it.

export interface Position {
  line: number;
  column: number;
}

interface SourceLocation {
  source?: string | null;
  start: Position;
  end: Position;
}

export interface BaseNode {
  type: string;
  loc?: SourceLocation | null;
  range?: [number, number];
}

export interface Comment extends BaseNode {
  type: "Line" | "Block";
  value: string;
}
`;

export default template;
